### PR TITLE
Fix/refactor unitview + remove avatars

### PR DESCRIPTION
**Pull request by TheKeyBlue**
FAForever/fa#1785 is necessary for this PR

Fixed the issues with the unitview
Removed avatars, since those changes can be in fa.

### CODE REVIEW

**Comment by TheKeyBlue** [comment]
Made some small changes to make it compatible with my latest and possibly future changes.
Mainly not hardcoding capacitator stat to spot 8 in the tables.

**Comment by CookieNoob** [comment]
can you redirect the PR to develop?

Since the PR on FAF was merged into deploy/FAFdevelop it will be published together with the next FAF patch (I will talk to icedreamer to make sure). The next game patch is planned for the 13.2.17 we can merge this if we release after that date (and I am sure we will not release earlier).

**Comment by CookieNoob** [comment]
ok, I talked to icedreamer. The calender is not up to date :/

The next game patch will be released when the new options menu is done. So it will be a while.

**Comment by CookieNoob** [comment]
I added an issue #104 that makes sure we dont release without the next gamepatch. So retarget and merge plz :)

**Comment by TheKeyBlue** [comment]
Is this what you wanted?
I did this btw: 
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by CookieNoob** [comment]
oh lol xD I didnt know that exists

yea its exactly what I wanted.

**Pull request merged**
